nameOverride: mon
grafana:
  enabled: false
  # defaultDashboardsEnabled: false
  # sidecar:
  #   dashboards:
  #     enabled: true
  #     label: grafana_dashboard
  #     provider:
  #       name: gitops
  #       folder: /var/lib/grafana/dashboards/gitops

admissionWebhooks:
  certManager:
    enabled: true