apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarkVortman/testtask
    targetRevision: main
    path: charts/spam
    helm:
      valueFiles:
        - ../../values/spam-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
